---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-${cert_manager_cloudflare_dns_secret_name_prefix}
  namespace: traefik
spec:
  secretName: traefik-${cert_manager_cloudflare_dns_secret_name_prefix}-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${traefik_dashboard_fqdn}"
  dnsNames:
    - "${traefik_dashboard_fqdn}"
