---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik=${traefik_cloudflare_dns_secret_name_prefix}
  namespace: traefik
spec:
  secretName: traefik-${traefik_cloudflare_dns_secret_name_prefix}-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "traefik.${traefik_cloudflare_dns_zone}"
  dnsNames:
    - "traefik.${traefik_cloudflare_dns_zone}"
