---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${cert_manager_cloudflare_dns_secret_name_prefix}
  namespace: cert-manager
spec:
  secretName: ${cert_manager_cloudflare_dns_secret_name_prefix}-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.${cert_manager_cloudflare_dns_zone}"
  dnsNames:
    - "${cert_manager_cloudflare_dns_zone}"
    - "*.${cert_manager_cloudflare_dns_zone}"
